### ISSUE TITLE
Win 11 support

### ISSUE THREAD

**Issue by Solomag** [hyp3rd/telegram-discord-bridge#33]
Hello, I tried to contact you on LinkedIn but couldn't reach you. After setting up all the files, I encountered this error. After some research, I realized that the script seems to only work on UNIX systems. Is it possible to add support for Windows systems, please?

```
C:\Users\Solo\telegram-discord-bridge>python forwarder.py --start
Traceback (most recent call last):
  File "C:\Users\Solo\telegram-discord-bridge\forwarder.py", line 326, in <module>
    controller(__start, __stop, __background)
  File "C:\Users\Solo\telegram-discord-bridge\forwarder.py", line 295, in controller
    start_bridge(loop)
  File "C:\Users\Solo\telegram-discord-bridge\forwarder.py", line 212, in start_bridge
    event_loop.run_until_complete(main())
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Solo\telegram-discord-bridge\forwarder.py", line 255, in main
    clients = await init_clients()
  File "C:\Users\Solo\telegram-discord-bridge\forwarder.py", line 164, in init_clients
    event_loop.add_signal_handler(
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 553, in add_signal_handler
    raise NotImplementedError
NotImplementedError
```

https://stackoverflow.com/questions/58014623/python-asyncio-notimplementederror

**Comment by hyp3rd** [comment]
The usage on Windows might have some limitations, but you can follow the progress from [this branch](https://github.com/hyp3rd/telegram-discord-bridge/tree/33-win-11-support).

I'll providing instructions also to run it in Docker.
